server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: media-service
          uri: http://media-service:8081
          predicates:
            - Path=/media/**
        
        - id: scraper-service
          uri: http://scraper-service:8082
          predicates:
            - Path=/scrape/**